language: python

python:
  - "3.7"

os:
  - linux

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

  - sudo docker run --rm -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=yourStrong_Password' -p 4433:1433 --name mssql1 -d mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
  - sudo docker run --rm -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=yourStrong_Password' -p 4434:1433 --name mssql2 -d mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
  - sudo docker ps

  - sudo docker cp data/sample_db_mssql1.sql mssql1:/tmp
  - sudo docker exec -it mssql1 /opt/mssql-tools/bin/sqlcmd -S 0.0.0.0 -U "SA" -P "yourStrong_Password" -i '/tmp/sample_db_mssql1.sql'

  - sudo docker cp data/sample_db_mssql2.sql mssql2:/tmp
  - sudo docker exec -it mssql2 /opt/mssql-tools/bin/sqlcmd -S 0.0.0.0 -U "SA" -P "yourStrong_Password" -i '/tmp/sample_db_mssql2.sql'

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls
