language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls

services:
  - 'mysql'
before_install:
  - mysql -u root --password="" < data/create_sample_database.sql
script:
  - scripts/run_tests travis
after_success:
  - coveralls
