language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls

services:
  - 'docker'
before_install:
  - make start_dev_db
script:
  - scripts/run_tests travis
after_success:
  - coveralls
