language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls

services:
  - 'docker'
before_install:
  - sudo docker cp data/sample_db_mssql1.sql mssql1:/tmp
  - sudo docker exec -it mssql1 /opt/mssql-tools/bin/sqlcmd \
        -S 0.0.0.0 -U "SA" -P "yourStrong_Password" \
        -i '/tmp/sample_db_mssql1.sql'

  - sudo docker cp data/sample_db_mssql2.sql mssql2:/tmp
  - sudo docker exec -it mssql2 /opt/mssql-tools/bin/sqlcmd \
       -S 0.0.0.0 -U "SA" -P "yourStrong_Password" \
       -i '/tmp/sample_db_mssql2.sql'

script:
  - scripts/run_tests travis
after_success:
  - coveralls
