#!/bin/bash
source flask/bin/activate
if [[ $1 ]] && [[ $1 = 'travis' ]]
then
   echo Travis detected: Initialising testing mysql database
   #mysql -u root --password="" < create_sample_database.sql
else
   echo No CI
fi

coverage run -m pytest
coverage report --omit=api/excel_op.py
coverage html
